services:
  leihsy-frontend:
    image: leihsy-frontend:latest
    ports:
      - "82:80"
    restart: unless-stopped
    networks:
      LeihSy:
        ipv4_address: 172.20.0.5

networks:
    LeihSy:
      external: true
