name: SonarQube Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Build and analyze Frontend
    runs-on: ubuntu-latest

    steps:
      # -----------------------------------------------------
      # Checkout repository
      # -----------------------------------------------------
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -----------------------------------------------------
      # Set up Node.js
      # -----------------------------------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # -----------------------------------------------------
      # Cache npm dependencies
      # -----------------------------------------------------
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm

      # -----------------------------------------------------
      # Install dependencies
      # -----------------------------------------------------
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # -----------------------------------------------------
      # Run Angular Unit Tests with coverage
      # -----------------------------------------------------
      - name: Run Angular Unit Tests with coverage
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      # -----------------------------------------------------
      # Build Angular frontend
      # -----------------------------------------------------
      - name: Build Angular frontend
        run: npm run build --if-present

      # -----------------------------------------------------
      # Set up Java 17 for SonarQube
      # -----------------------------------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # -----------------------------------------------------
      # SonarQube Scan
      # -----------------------------------------------------
      - name: SonarQube Scan Frontend
        uses: SonarSource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
